#Задача 1 (Код Морзе)

morse = input()

morse = morse.replace('..-..', 'э')
morse = morse.replace('-...', 'б')
morse = morse.replace('...-', 'ж')
morse = morse.replace('--..', 'з')
morse = morse.replace('.---', 'й')
morse = morse.replace('.-..', 'л')
morse = morse.replace('.--.', 'п')
morse = morse.replace('..-.', 'ф')
morse = morse.replace('....', 'х')
morse = morse.replace('-.-.', 'ц')
morse = morse.replace('---.', 'ч')
morse = morse.replace('----', 'ш')
morse = morse.replace('--.-', 'щ')
morse = morse.replace('-..-', 'ь')
morse = morse.replace('-.--', 'ы')
morse = morse.replace('..--', 'ю')
morse = morse.replace('.-.-', 'я')
morse = morse.replace('.--', 'в')
morse = morse.replace('--.', 'г')
morse = morse.replace('-..', 'д')
morse = morse.replace('-.-', 'к')
morse = morse.replace('---', 'о')
morse = morse.replace('.-.', 'р')
morse = morse.replace('...', 'с')
morse = morse.replace('..-', 'у')
morse = morse.replace('.-', 'a')
morse = morse.replace('..', 'и')
morse = morse.replace('--', 'м')
morse = morse.replace('-.', 'н')
morse = morse.replace('.', 'е')
morse = morse.replace('-', 'т')

morse = morse.replace(' ', '')
morse = morse.replace('/', ' ')
morse = morse.replace('End', '')

print(morse)
